### ISSUE TITLE
开启提示有错误

### ISSUE THREAD

**Issue by Leeiiiii** [babalae/mihoyo-starter#1]
<img width="328" alt="MiHoYoStarter_0501_181812" src="https://user-images.githubusercontent.com/38080054/235439892-6c1ca07d-5c63-4c4e-9814-6f4066e574c7.png">
选择继续后程序可以运行，添加路径按钮无反应。（我的游戏目录是自定义的，因为前面系统重装之后，我用启动器自己定位了一下）
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentNullException: 值不能为 null。
参数名: path1
   在 System.IO.Path.Combine(String path1, String path2, String path3)
   在 MiHoYoStarter.GameFormControl.InitControl(FormMain formMain, TabPage tabPage, String pathSetting)
   在 MiHoYoStarter.FormMain.FormMain_Load(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ContainerControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

以下为详细错误

**Comment by Leeiiiii** [comment]
发现错误了，点路径无法打开。

**Comment by huiyadanli** [comment]
看了下报错位置，原因目测是程序没法获取到当前运行的路径。

你是不是没有解压就运行了程序

**Comment by Leeiiiii** [comment]
呃 这种低级错误肯定不可能啊

**Comment by Leeiiiii** [comment]
这种低级错误肯定不可能啊，刚看了下注册表，是不是因为我的注册表里面根本没有安装路径的信息造成的，因为我是重装的，里面根本没有米哈游相关的路径信息
<img width="951" alt="regedit_0501_193727" src="https://user-images.githubusercontent.com/38080054/235446638-e4aa3394-8fee-4183-8df4-17995233e426.png">
但是这样会造成选择路径的按钮无效吗，也不应该啊。

**Comment by huiyadanli** [comment]
[MiHoYoStarter_1.6_fix.zip](https://github.com/babalae/mihoyo-starter/files/11365413/MiHoYoStarter_1.6_fix.zip)

**Comment by Leeiiiii** [comment]
能上传下修复版本的源码我研究研究吗~谢谢了。

**Comment by Leeiiiii** [comment]
试了一下可以了，但是切换的时候会有命令行窗口闪现，另外能不能加个切换后自动重启的选项，感觉这样会更方便一点。
1.5版本我自己改了个云原神的，。

**Comment by huiyadanli** [comment]
现在默认是切换时候自动重启的

**Comment by Leeiiiii** [comment]
<img width="865" alt="0502_122752" src="https://user-images.githubusercontent.com/38080054/235579866-a441a13f-a45b-405f-8199-c3f5faf90c9d.png">
我知道问题出在哪里了，前面一直试的云原神，我就发现不能启动程序，就弹了一下命令行窗口，太快了，我也没注意。刚才来试原神，就发现问题所在了。可能你那边测试的是从注册表读取安装路径，所以就没有这个逻辑问题。
但是我看了下1.5的代码，是手动选主目录后会定位相关exe执行文件（我自己改的云原神就是修改了相关定位的，因为我代肝嘛，得用云原神上资源号。双开原神电脑顶不住~~~），你这个1.6应该是没加这个判断，所以找不到exe路径。
从运行原神的窗口就看出来了，他开始遍历整个目录了。
然后手动补齐路径后就能运行了（所以我一开始以为是没设置自动重启，因为没反应），建议启动路径浏览界面直接定位exe文件，会直观很多。选择目录的话貌似判断什么的也要麻烦些。
可能这个问题对于一般安装正常的玩家来说不会出这个bug，我这正好是重装了，懒得下，就恰好遇到这个问题了。

**Comment by Leeiiiii** [comment]
<img width="289" alt="MiHoYoStarter_0502_130203" src="https://user-images.githubusercontent.com/38080054/235583232-ff83d5ae-1407-49c9-8b8d-cb63caed518b.png">
<img width="289" alt="MiHoYoStarter_0502_130143" src="https://user-images.githubusercontent.com/38080054/235583254-6aaf243c-7294-4a1d-93a8-215b9f9634c4.png">
默认添加目录后就不会自动添加搜寻exe文件，应该就是这个原因，直接定位exe感觉会好很多啊。

**Comment by huiyadanli** [comment]
是我去掉了老版本对路径二次校验的判断（老版本只需要到目录）。。实际要定位到具体游戏本体exe的，不是目录级别，我把校验加回去吧hhh

我文档也写了：
>
1. 切换时会自动重启游戏（所以要求填写游戏本体路径），可以在托盘图标处点击账号进行切换。
2. 正常情况下，游戏目录会自动从注册表游戏安装信息中读取，个别情况下会读取不到（你可能移动过游戏目录），此时需要手动选择游戏本体目录，注意不是游戏启动程序目录！以下是游戏本体路径：
    * 原神(国服)：`\Genshin Impact\Genshin Impact Game\YuanShen.exe`
    * 云·原神：`\Genshin Impact Cloud Game\Genshin Impact Cloud Game.exe`
    * 崩坏：星穹铁道：`\Star Rail\Game\StarRail.exe`

所以你定位到具体的游戏本体exe就可以了。
我优化下这块的使用体验和校验

**Comment by Leeiiiii** [comment]
<img width="439" alt="MiHoYoStarter_0502_131607" src="https://user-images.githubusercontent.com/38080054/235584491-12f72a21-1b6a-4062-ade9-3f0787a69939.png">
问题就出在这里啊，用的浏览文件夹的控件，定位不到exe。。。

**Comment by huiyadanli** [comment]
我的问题，忘记改选择器了:joy:

**Comment by huiyadanli** [comment]
[MiHoYoStarter.1.7.zip](https://github.com/babalae/mihoyo-starter/files/11370041/MiHoYoStarter.1.7.zip)

试试这个，应该没问题了

**Comment by Leeiiiii** [comment]
试了下，功能应该没问题了。谢谢~
但从体验优化的角度讲还有几个地方可以优化一下。（当然这个需求只对有大量账号的人有用哈哈哈，不过点窗口也没事）
不过从逻辑上也应该这样设计。
<img width="1280" alt="explorer_0502_135719" src="https://user-images.githubusercontent.com/38080054/235590254-da6becf2-3195-4029-8aa5-f55f27e30581.png">
托盘弹窗应该设置一个最大尺寸，显示主窗口和退出按钮应该保持一直可见（不能被大量账号覆盖），账号区域超出范围后应该设置滚动条。

**Comment by huiyadanli** [comment]
感谢你的测试和反馈。

托盘的右键菜单要实现这种模式有点难，要重写右键菜单控件，或者直接使用三方控件。感觉可以用二级菜单进行分组收纳。这块暂时就不改了。

**Comment by Leeiiiii** [comment]
所以其实没多大影响，正常玩家用不到的。
