### ISSUE TITLE
希望能增加国际服支持

### ISSUE THREAD

**Issue by TheTychoStar** [babalae/mihoyo-starter#14]
国际服的原理应该也是一样的，登录信息保存在注册表里，感觉加一个国际服难度应该是很低的。
我看了下好像需要的是这几个信息？如果还需要什么我可以提供。

- 国际服的注册表路径：`HKEY_CURRENT_USER\Software\miHoYo\Genshin Impact`
- 注册表项：`MIHOYOSDK_ADL_PROD_OVERSEA_h1158948810`

**Comment by huiyadanli** [comment]
* 注册表安装信息：`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Genshin Impact`

* 文件目录 `Genshin Impact Game\GenshinImpact.exe`

**Comment by huiyadanli** [comment]
https://github.com/babalae/mihoyo-starter/releases/tag/2.0

已经添加原神国际服支持，不过我这边没条件测试
