### ISSUE TITLE
国服与国际服分开标签页

### ISSUE THREAD

**Issue by earthjasonlin** [babalae/mihoyo-starter#18]
现在国服和国际服好像是一个下拉列表来选的，如果分开标签页的话逻辑会更清晰

**Comment by huiyadanli** [comment]
我刚刚还在考虑这个问题来着，有时间重写下

**Comment by huiyadanli** [comment]
[MiHoYoStarter_2.1.beta1.zip](https://github.com/babalae/mihoyo-starter/files/12567506/MiHoYoStarter_2.1.beta1.zip)

测试下，老的账号信息应该就没用了
