### ISSUE TITLE
能不能再加一个启动客户端的按钮，游戏更新的时候也可以用这个软件调用

### ISSUE THREAD

**Issue by NOWorEVER** [babalae/mihoyo-starter#19]
能不能再加一个启动客户端的按钮，游戏更新的时候也可以用这个软件调用
![image](https://github.com/babalae/mihoyo-starter/assets/57054154/5bbd6623-d654-41cd-a3fa-9ddaf496c1cf)

**Comment by huiyadanli** [comment]
直接从游戏快捷方式打开岂不是更快
