### ISSUE TITLE
一些可能的优化建议

### ISSUE THREAD

**Issue by WorldlineChanger** [babalae/mihoyo-starter#2]
从Akebi-injector使用发现的一些不同，个人而言更加方便一些

1. 启动时窗口居中，和上个项目一致
2. 保存账号时也可以保存游戏画面设置
3. 目前最小化后，alt+tab仍然会显示窗口

![snipaste_20230505_175145](https://user-images.githubusercontent.com/46261730/236520711-7888a2f8-d89a-4204-8e7b-bed4b160edac.jpg)

**Comment by huiyadanli** [comment]
额，这个界面不是和我写的老版本的一模一样么。这个功能因为用的人太少，被我砍了。。

搜了下是我这边重写前老版本的fork
https://github.com/babalae/genshin-account
https://github.com/hellomykami/genshin-account

**Comment by huiyadanli** [comment]
1、3我改进下，复制粘贴的时候没注意

**Comment by WorldlineChanger** [comment]
> 1、3我改进下，复制粘贴的时候没注意

感谢大佬👍

**Comment by huiyadanli** [comment]
https://github.com/babalae/mihoyo-starter/releases/tag/1.8

1.8 版本优化了  1、3 的问题，试试

**Comment by WorldlineChanger** [comment]
> https://github.com/babalae/mihoyo-starter/releases/tag/1.8
> 
> 1.8 版本优化了 1、3 的问题，试试

大佬强的，重新添加试了下都没问题。画面设置的需求是因为我平时挂机时会调最低，但调回去的时候没有真正最高的选项，还得手动回调。不过老版本用着也没什么问题就是了，赞美大佬
