### ISSUE TITLE
问大佬个问题

### ISSUE THREAD

**Issue by ABC20232001** [babalae/mihoyo-starter#20]
使用了两次，但是第三次程序内双击点开登陆的时候发现账号信息掉了，这是什么情况呢？求解答

**Comment by huiyadanli** [comment]
正常现象，重新保存继续使用就行。

**Comment by ABC20232001** [comment]
啊，好的哦，谢谢解答，我这不算提建议，我把这个问题删了

> 正常现象，重新保存继续使用就行。
