### ISSUE TITLE
[BUG]启动B站账号的时候启动的却是官服账号

### ISSUE THREAD

**Issue by yinghaodang** [babalae/mihoyo-starter#22]
我下载了2.1版本的程序，运行之后我设置了B服的游戏本体路径：`D:\Star Rail Bilibili\Star Rail\Game\StarRail.exe`
我能够从Windows的任务管理器看到启动的可执行文件是这个StarRail.exe。
但是进入游戏时候，登录的账号是我官服的账号。

我的官服账号在这个地址：`D:\Star Rail\Game\StarRail.exe`。

我使用鼠标分别点击上面提到的两个可执行文件可以正常进入对应的服务器。

我猜测这些可执行文件都是一样的，只不过一些类似环境变量的配置信息不一样？然后软件在执行`D:\Star Rail Bilibili\Star Rail\Game\StarRail.exe`的时候，误读取了官服的配置文件？

这方面的知识应该去哪里学习？理论上B服和官服使用一套游戏数据行不行？
![银狼](https://github.com/babalae/mihoyo-starter/assets/49315320/e7208fe9-d53c-4027-9f57-c0cda1b42c41)

**Comment by huiyadanli** [comment]
`WorkingDirectory = Path.GetDirectoryName(path)`
