### ISSUE TITLE
切换账号失败

### ISSUE THREAD

**Issue by Jonathan-Wade** [babalae/mihoyo-starter#23]
保存好账号后，可以切换账号。
但是，但是，那个电脑重启开机后，切换账号无用，要自己重新登录。

**Comment by huiyadanli** [comment]
跟服务器对你账号的风控策略有关。

和账号切换功能无关

**Comment by Jonathan-Wade** [comment]
但是，这个功能在我朋友电脑上，是可以的？

**Comment by huiyadanli** [comment]
你的电脑环境，ip信息都是风控的要素之一。这个账号在不同的环境肯定是不同的风控结果。

你可以换其他切换账号工具试试，结果应该是一样的

**Comment by Jonathan-Wade** [comment]
ok，确实是这样，其他工具一样在电脑重启后无用了
