### ISSUE TITLE
请求支持绝区零

### ISSUE THREAD

**Issue by nyano** [babalae/mihoyo-starter#25]
大佬我爱你。
另外建议加个按钮，直接可以打开软件申请管理员权限，不需要一个一个点的时候申请UAC了。
虽然我知道快捷方式里可以加

**Comment by qsuron0** [comment]
我已经添加完毕【https://github.com/babalae/mihoyo-starter/pull/26】，代码提交了，等他合并即可。或者你到我的项目里面去下载。
