### ISSUE TITLE
2.2版本 显示界面仍然为2.1

### ISSUE THREAD

**Issue by labandoyle** [babalae/mihoyo-starter#27]
首先感谢快速支持绝绝区零的更新，但是新更新的这个版本 有俩问题
1、首页显示的还是 2.1版本
2、新更新之后 窗口框体特别大。而且调整缩放后，重新打开还是恢复了原来的窗体大小
3、标签显示的顺序也是重新打开后会恢复，比如默认第一个显示的是绝区零，原本通过先取消勾选绝区零 再勾上，可以让这个标签页挪到最后面，但是关闭再打开又跳到第一个位置了

![微信图片_20240710121140](https://github.com/babalae/mihoyo-starter/assets/54054588/b599c989-c9a7-40ed-8acd-b5dc736dd098)

**Comment by STC214** [comment]
+1

**Comment by nyano** [comment]
楼上居然把zzz安装在c盘。

2.2 BUG
-绝区零明明在最后，但是每次启动软件，放在了第一列
-任务栏右键账户里，没有绝区零

**Comment by huiyadanli** [comment]
3是历史问题，暂时不做修改

**Comment by huiyadanli** [comment]
2.3 已经修复上述问题
