### ISSUE TITLE
希望取消或者增加画面120FPS开关

### ISSUE THREAD

**Issue by xiaolizi-zlkj** [babalae/mihoyo-starter#28]
我只是希望有一个账号登陆管理器，而不是调整游戏的设置，我不希望因此导致不必要的游戏账号安全问题（怕被官方检测而封号）
目前的120FPS我无法确定我是否开启或关闭了此功能，每次我都需要手动调整为60FPS，然后保存，以确定我的担忧

**Comment by huiyadanli** [comment]
完全看不懂你在说什么。

这里只有星铁修改了120帧，而且是无风险的游戏内配置（游戏内配置！游戏内配置！游戏内配置！是游戏提供的配置！），你完全可以把配置改到60帧启动啊
