### ISSUE TITLE
After losing account information, it is not possible to log in normally when using the tool to start

### ISSUE THREAD

**Issue by gqzcl** [babalae/mihoyo-starter#3]
### What happened

After the system restarts, using tools to start the game does not enter the login state

![IY~({3FKP5C B_P NIFUX7O](https://github.com/babalae/mihoyo-starter/assets/43192463/012299c6-febb-4c0d-94cb-335d99631633)

### Additional information

System updated

**Comment by huiyadanli** [comment]
老毛病了，重新登录保存下账号就行
