### ISSUE TITLE
启动报错.NET

### ISSUE THREAD

**Issue by Kokyuumusou13** [babalae/mihoyo-starter#30]
![Image](https://github.com/user-attachments/assets/04b8bae2-cdba-4fc5-a00f-e99b9d038d17)

设备环境：Windows 11 家庭中文版 23H2，i7-12650H
以前一直都可以使用2.1.0.0版本的，今天突然报错，选择继续后程序可以运行，且丢失了所有账号记录
同时我发现电脑上一些其他软件也无法使用，如VK加速器无法获取任何加速节点，未能成功配置网卡，VK日志里也记录到了.NET的问题

在提问前，我排查确认了网络、驱动均无问题，从官方启动器打开原神可正常游玩，尝试安装.NET Framework 4.8.1但提示已安装
，检索相关问题并尝试删除%AppData%\Local\MiHoYoStarter\MiHoYoStarter.exe_Url_jjhtbheyicb5tvhjw1w3bl2m4dufu1pz\2.1.0.0路径下的user.config文件，尝试使用2.3.0.0版的MiHoYoStarter，也多次重启过电脑，均无法解决问题，请大佬帮忙看一下吧，已经是重装系统前最后的挣扎

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Configuration.ConfigurationErrorsException: 配置节“connectionStrings”具有意外的声明。
   在 System.Configuration.ConfigurationManager.get_ConnectionStrings()
   在 System.Configuration.PrivilegedConfigurationManager.get_ConnectionStrings()
   在 System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   在 System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   在 System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   在 System.Configuration.SettingsBase.get_Item(String propertyName)
   在 System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   在 System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   在 MiHoYoStarter.Properties.Settings.get_GenshinPath()
   在 MiHoYoStarter.FormMain.FormMain_Load(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.ContainerControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.9282.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MiHoYoStarter
    程序集版本:2.3.0.0
    Win32 版本:2.3.0.0
    基本代码:file:///C:/Users/kokyuu13/Desktop/Game%26Platforms/MiHoYoStarter.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.9251.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.9282.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.9277.0 built by: NET481REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.resources/v4.0_4.0.0.0_zh-Hans_b03f5f7f11d50a3a/System.Configuration.resources.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Management
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Web.Extensions
    程序集版本:4.0.0.0
    Win32 版本:4.8.9282.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    程序集版本:4.0.0.0
    Win32 版本:4.8.9282.0 built by: NET481REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Web.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.resources/v4.0_4.0.0.0_zh-Hans_b03f5f7f11d50a3a/System.Web.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.9032.0 built by: NET481REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by huiyadanli** [comment]
尝试卸载系统中其他版本的.NET Framework，尝试重新安装 .NET Framework 4.5.2

**Comment by Kokyuumusou13** [comment]
![Image](https://github.com/user-attachments/assets/af6fcb38-d14e-4cd3-a689-453c7d59b637)

感谢解答，在我“使用Windows更新修复问题”后，未删除任何个人文件和应用，重装了现版本Windows，这一步也包含了重装.NET Framework，问题已得到解决，成功打开MiHoYoStarter且有历史账号记录。回来了都回来了
