### ISSUE TITLE
大佬你好，可以支持一下崩三吗，我看也是和原神一样的

### ISSUE THREAD

**Issue by gqzcl** [babalae/mihoyo-starter#5]
![image](https://github.com/babalae/mihoyo-starter/assets/43192463/43ca1bcf-eaf6-4532-9371-bc47911fd85d)

**Comment by huiyadanli** [comment]
启动器安装路径：
![image](https://github.com/babalae/mihoyo-starter/assets/15783049/d004ea77-5860-412f-9b3f-482ec2eed9c1)

还差个游戏进程名

**Comment by huiyadanli** [comment]
[MiHoYoStarter.zip](https://github.com/babalae/mihoyo-starter/files/11471356/MiHoYoStarter.zip)

写完了，测试下

**Comment by gqzcl** [comment]
![image](https://github.com/babalae/mihoyo-starter/assets/43192463/99116d0e-e5c0-48a1-934d-d2a5a26113ee)

这里默认的会选不到游戏的启动程序

**Comment by huiyadanli** [comment]
已支持
https://github.com/babalae/mihoyo-starter/releases/tag/1.9
