### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by qq57240** [babalae/mihoyo-starter#6]
崩铁原生支持多开，建议启动器在启动新进程时不要关闭原进程，或者添加选项可选是否使用多开。

**Comment by huiyadanli** [comment]
原来如此，崩铁直接多开多账号也行吗？

多开后，全部关掉，然后再启动，默认登录的是最近一次登录的账号吗？

**Comment by qq57240** [comment]
> 原来如此，崩铁直接多开多账号也行吗？
> 
> 多开后，全部关掉，然后再启动，默认登录的是最近一次登录的账号吗？

多开全部关掉后默认登录就是最后一次登录的账号，这个逻辑没改变。

**Comment by huiyadanli** [comment]
已放出最新版
https://github.com/babalae/mihoyo-starter/releases/tag/1.9
